blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :articles
  
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
end

blog/app/models/post.rb
class Post < ApplicationRecord
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def new
	end

	def index
	end
	
	def create
  #C Если теперь еще раз отправить форму, на странице ничего не поменяется. Не беспокойтесь! Это так, потому что Rails по умолчанию возвращает отклик 204 No Content для экшна, если мы не указали, какой должен быть отклик. Мы просто добавили экшн create, но не указали ничего о том, каким должен быть отклик. В нашем случае, экшн create должен сохранить нашу новую статью в базу данных.

  #При отправке формы, ее поля будут посланы в Rails как параметры. К этим параметрам можно обратиться из экшнов контроллера, как правило, для выполнения определенных задач. Чтобы увидеть, на что похожи эти параметры, измените экшн create так:
  render plain: params[:article].inspect
  #Тут метод render принимает очень простой хэш с ключом :plain и значением params[:article].inspect. Метод params это объект, представляющий параметры (или поля), приходящие от формы. Метод params возвращает объект ActionController::Parameters, позволяющий получать доступ к ключам хэша с использованием или строк, или символов. В этой ситуации имеют значение только параметры, пришедшие от формы.
  ###Убедитесь, что у вас есть твердое понимание метода params, так как вы будете его использовать очень часто. Давайте рассмотрим в качестве примера URL: http://www.example.com/?username=dhh&email=dhh@email.com. В этом URL, params[:username] будет равен "dhh" и params[:email] будет равен "dhh@email.com".###
	end

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/articles/index.html.erb
<h1>COUSES</h1>

<a href="/articles/ruby"><h2>Ruby</h2></a>

<a href="/articles/ruby_on_rails5"><h2>Ruby on Rails 5</h2></a>

blog/app/views/articles/new.html.erb
<h1>Course 1</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/articles/ruby.html.erb
<h1>popitka ne pitka</h1>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <h1>Hello there! It is my RUBY course</h1>
  <h2>Lesson 1</h2>
  <p>
    use 'puts' to show some text
    but inside the app we use special tags < % =
    <%=  "Some text" %> % >
    <br> Do you know that this text "<%=  "Some text" %>" is running using embedded ruby? Cool, yeah?
  </p>
  <p>
    Now i want to create a variable. To do it I have to type something in that tags < % =
     % > and to add space and "=" sign and than value in quotes " ". Like this. Oh. We can use HTML tags for you to understand what we are talking about.
     <i><%=  "This text is beeing generated using embedded RUBY or .erb" %></i>
     <br>This text is just structured by HTML.
    <br><% so = "So, what we can do with ruby?" %>
    <i><%= so %></i> - text from variable called "so"
    <br>
    We can do something with strings, for ex we can make interpolation: to do it we need to write:
    <br> < % google ="Google" % > < %= google % > And it will give us:
    <br><% google ="Google" %>
    <i><%= google %></i>
    <br> But now we can do  < %= "Hello #{google}" % > And it will give us:
    <br><i><%= "Hello #{google}" %></i>
    I HAVE DONE IT!
  </p>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>